import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { uuid } from "uuidv4";
import { env } from "~/env.mjs";
import styles from "./index.module.css";

const Home: NextPage = () => {
  const [token, setToken] = useState<string>();
  useEffect(() => {
    async function login() {
      const payload = {
        method: "login",
        params: {
          appType: "Kasa_Android",
          cloudUserName: env.NEXT_PUBLIC_TPLINK_USER,
          cloudPassword: env.NEXT_PUBLIC_TPLINK_PASSWORD,
          terminalUUID: uuid(),
        },
      };
      await fetch("https://wap.tplinkcloud.com/", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(payload),
      })
        .then((response) => response.json())
        .then((data: { result: { token: string } }) => {
          setToken(data.result.token);
        });
    }
    login().catch((e) => console.error(e));
  }, []);

  return (
    <>
      <Head>
        <title>Lights</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            <span className={styles.pinkSpan}>Lights</span>
          </h1>
          <h3>
            <span className={styles.pinkSpan}>{token ?? "Loading..."}</span>
          </h3>
          <div className={styles.cardRow}>
            {/* <Link
              className={styles.card}
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>First Steps →</h3>
              <div className={styles.cardText}>
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className={styles.card}
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className={styles.cardTitle}>Documentation →</h3>
              <div className={styles.cardText}>
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link> */}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
